[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autorestart=true

[program:openclaw]
# OpenClaw hazır olduğunda komutunuzu buraya ekleyeceksiniz. 
command=sleep infinity
autorestart=true
